#!/bin/bash

# Clear macOS screenshots from Desktop folder and move them to a screenShots folder.

cd ~
mv Desktop/ScreenShot* screenShots/
mv Desktop/Screen\ Shot* screenShots/
mv Desktop/*.png screenShots/
mv Desktop/*.jpg screenShots/
mv Desktop/*.jpeg screenShots/
