#!/bin/bash

# Get url file with auth
# example: script.sh <user> <token> <url>

ARGS_NUM=3
if [[ ( $# -lt $ARGS_NUM ) ]]; then
  echo "Usage: script.sh <user> <token> <url>"
  exit 1
fi

curl --user $1:$2 --silent $3
