#!/bin/bash

# Clean containters and images of docker.

#Stop containers
docker stop $(docker ps -a -q)

#Remove docker containers:
docker rm $(docker ps -a -f status=exited -q)

# Remove docker images:
docker rmi -f $(docker images -a -q)

# Remove dangling networks:
docker network prune -f

# Remove dangling volumes:
# docker volume prune -f

# remove all volumes:
docker volume rm $(docker volume ls -q)