#!/bin/bash

# Clean containters and images of docker.

# check if docker is online and close the script otherwise
if ! docker info > /dev/null 2>&1; then
    echo "Docker is not running. Exiting..."
    echo " - MacOS: open -a Docker"
    echo " - ubuntu: sudo systemctl restart docker"
    exit 1
fi

#Stop containers
docker stop $(docker ps -a -q)

#Remove docker containers:
docker rm $(docker ps -a -f status=exited -q)
docker rm $(docker ps -a -f status=created -q)

# Remove docker images:
docker rmi -f $(docker images -a -q)

# Remove dangling networks:
docker network prune -f

# Remove dangling volumes:
docker volume prune -f

# remove all volumes:
docker volume rm $(docker volume ls -q)