#!/bin/bash

# rename for OSX, taken from https://stackoverflow.com/a/48738544

ARGS_NUM=2
if [[ ( $# -lt $ARGS_NUM ) ]]; then
  echo "Usage: script.sh ORIGINAL CHANGED"
  exit 1
fi

for i in $1*
do
    mv "$i" "${i/$1/$2}"
done