#!/bin/bash

# Save all stashes, credit to @ordepdev, https://stackoverflow.com/a/48299431/7468990

mkdir temp-saved-stashes
cd temp-saved-stashes

git stash list | sed 's/\//\_/g'|sed 's/ /\_/g' | awk -F ":" '{ system("git stash show -p " $1 " >> " $1$2$3 ".diff" ) }'

